CS577 Assignment 0
Spring 2021
Shivi Srivastava

In [3]:
import numpy as np
from random import randint, uniform, random
import math

In [17]:

#A.--------------------------------------------------------------------------------------
#a= np.array([1,2,3])
a= np.array([[1],[2],[3]])
b= np.array([[4],[5],[6]])
c= np.array([[-1],[1],[3]])

print(b)

[[4]
 [5]
 [6]]


In [18]:
#A.1: 2A-B
a1=2*a-b
print(a1)

[[-2]
 [-1]
 [ 0]]


In [143]:
#A.2: Av unit direction of A
a31=a/a21
print(a31)

[[0.2672582 ]
 [0.5345164 ]
 [0.80177459]]


In [142]:
#A.3: ||A|| and angle relative to X axis
a21=round(np.linalg.norm(a),4)
a22=round(np.rad2deg(np.arccos(1/a21)),4)
print("The ||A|| is: "+str(a21)+" and the angle realtive to X axis is: "+str(a22)+" degrees")

The ||A|| is: 3.7417 and the angle realtive to X axis is: 74.4988 degrees


In [144]:
#A.4: direction of cosines of A
a41=(a[0]/a21)
a42=(a[1]/a21)
a43=(a[2]/a21)
print("The directions cos(x), cos(y) & cos(z) are : "+str(a41)+", "+str(a42)+" & "+str(a43)+" respectively")


The directions cos(x), cos(y) & cos(z) are : [0.2672582], [0.5345164] & [0.80177459] respectively


In [33]:
#A.5: Angle between A and B
a51= np.dot(np.squeeze(np.asarray(a)),np.squeeze(np.asarray(b)))
a52= (np.linalg.norm(a))*(np.linalg.norm(b)) 
a53= round(np.rad2deg(np.arccos(a51/a52)),4)
print(a53)

12.9332


In [163]:
#A.6: a.b and b.a
a61=np.dot(np.squeeze(np.asarray(a)),np.squeeze(np.asarray(b)))
a62=np.dot(np.squeeze(np.asarray(b)),np.squeeze(np.asarray(a)))
print("A.B = "+str(a61)+" = B.A")

A.B = 32 = B.A


In [35]:
#A.7 
a71= round(np.linalg.norm(a),4)*round(np.linalg.norm(b),4)
a72= round(a71*np.cos(a53),4)
print(a72)

30.649


In [146]:
#A.8 The scalar projection of b onto a
a53=a51/a21
print(a53)

8.5522623406473


In [148]:
#A.9 A vector whic is perpendicular to a
a91=np.array([randint(0,10),randint(0,10),randint(0,10)])
a92=np.cross(a91,np.squeeze(np.asarray(a)))
a93= np.dot(a92,np.asarray(a))
print(a92)
print(str(a93)+"; if a93 is 0 then vector is perpendicular to a")

[27 -3 -7]
[0]; if a93 is 0 then vector is perpendicular to a


In [149]:
#A.10: axb and bxa
a101=np.cross(np.squeeze(np.asarray(a)),np.squeeze(np.asarray(b)))
a102=np.cross(np.squeeze(np.asarray(b)),np.squeeze(np.asarray(a)))
print("axb = "+str(a101))
print("bxa = "+str(a102))

axb = [-3  6 -3]
bxa = [ 3 -6  3]


In [150]:
#A.11: vector perpendicular to A and B
print("AxB = "+str(a101))

AxB = [-3  6 -3]


In [151]:
#A.12: dependency between A, B & C
d=[np.squeeze(np.asarray(a)),np.squeeze(np.asarray(b)),np.squeeze(np.asarray(c))]
print("|D|=",round(np.linalg.det(d)))

|D|= 0


In [152]:
#A.13: At.B & A.Bt
#a= np.matrix([1]) #transpose on matrix not array
#b= np.matrix([4,5,6])
c= np.matrix([-1,1,3])
a111= a.transpose()
a133=np.dot(a111,b)
a112= a*b.transpose()
print("At.B = ")
print(a133)
print("A.Bt = ")
print(a112)

At.B = 
[[32]]
A.Bt = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [5]:

#B.--------------------------------------------------------------------------------------
aa= np.array([[1,2,3],[4,-2,3],[0,5,-1]])
bb= np.array([[1,2,1],[2,1,-4],[3,-2,1]])
cc= np.array([[1,2,3],[4,5,6],[-1,1,3]])
dd= np.array([[1],[2],[3]])

In [155]:
#B.1: 2A-B
b1=2*aa-bb
print(b1)

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [165]:
#B.2: A.B & B.A
b21= np.dot(aa,bb)
b22= np.dot(bb,aa)
print("A.B = ")
print(b21)
print("B.A = ")
print(b22)

A.B = 
[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
B.A = 
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [166]:
#B.3: (AB)t & Bt*At
b31= b21.transpose()
b32= np.dot(bb.transpose(),aa.transpose())
print("(A.B)t = ")
print(b31)
print("Bt.At = ")
print(b32)

(A.B)t = 
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
Bt.At = 
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [167]:
#B.4: |A| & |C|
b41=np.linalg.det(aa)
b42=np.linalg.det(cc)
print("|A| = "+str(round(b41,1)))
print("|C| = "+str(round(b42,1)))

|A| = 55.0
|C| = 0.0


In [169]:
#B.5: orthogonal set of A, B & C
b51= np.dot(aa,aa.transpose())
b52= np.dot(bb,bb.transpose())
b53= np.dot(cc,cc.transpose())
print("A.At = ")
print(b51)
print("B.Bt = ")
print(b52)
print("C.Ct = ")
print(b53)

A.At = 
[[ 14   9   7]
 [  9  29 -13]
 [  7 -13  26]]
B.Bt = 
[[ 6  0  0]
 [ 0 21  0]
 [ 0  0 14]]
C.Ct = 
[[14 32 10]
 [32 77 19]
 [10 19 11]]


In [184]:
#B.6 A inverse and B inverse
b61=np.linalg.inv(aa).round(4,)
b62=np.linalg.inv(bb).round(4,)
print("A inverse = ")
print(b61)
print("B inverse = ")
print(b62)

A inverse = 
[[-0.2364  0.3091  0.2182]
 [ 0.0727 -0.0182  0.1636]
 [ 0.3636 -0.0909 -0.1818]]
B inverse = 
[[ 0.1667  0.0952  0.2143]
 [ 0.3333  0.0476 -0.1429]
 [ 0.1667 -0.1905  0.0714]]


In [204]:
#B.7 C inverse
try:
  b71=np.linalg.inv(cc).round(4,)
  print("C inverse = ")
  print(b71)
         
except np.linalg.LinAlgError as err:
        # your error handling block
        print(str(err))
        


Singular matrix


In [210]:
#B.8 Ad
b81= np.dot(aa,dd)
print("Ad : ")
print(b81)

Ad : 
[[14]
 [ 9]
 [ 7]]


In [62]:
#B.10 The linear combination of columns of A using the elements of D
b101= np.asarray(aa)
b102= np.hsplit(b101, 3)
b103= (dd[0]*b102[0])+(dd[1]*b102[1])+(dd[2]*b102[2])
print(b103)

[[14]
 [ 9]
 [ 7]]


In [71]:
#B.11 solution x for the equation Bx=d
xb11= np.linalg.solve(bb, dd)
print("Value of x: ")
print(xb11);
np.allclose(np.dot(bb, xb12), dd)

Value of x: 
[[ 1.00000000e+00]
 [ 2.37904934e-17]
 [-1.18952467e-17]]


True

In [74]:
#B.12 solution x for the equation Cx=d
try:
  xb12= np.linalg.solve(cc, dd)
  print("Value of x: ")
  print(xb12);
  np.allclose(np.dot(cc, xb12), dd)
except np.linalg.LinAlgError as err:
        # your error handling block
        print(str(err))


Singular matrix


In [76]:
#C.--------------------------------------------------------------------------------------
ddd= np.array([[1,2],[3,2]])
eee= np.array([[2,-2],[-2,5]])
fff= np.array([[1,2],[2,4]])

In [12]:
#C.1: eigenvalues and eigenvectors of D
c11, c12= np.linalg.eig(ddd)
print("The eigenvalues are = "+ str(c11[0]) + " & "+ str(c11[1]))
print("The eigenvectors are =")
print(c12)

The eigenvalues are = -1.0 & 4.0
The eigenvectors are =
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [11]:
#C.2: dot products between eigenvectors of D
c21= np.dot(c12[0],c12[1])
print(c21)

-0.038461538461538214


In [13]:
  #C.3: dot products between eigenvectors of E
c31, c32= np.linalg.eig(eee)
c33= np.dot(c32[0],c32[1])
print(c33)

-1.2594923403361582e-17


In [84]:
#C.5 the only solution x to the equation Fx=0
try:
  c51=np.array([0, 0])
  xc52= np.linalg.solve(fff, c51)

  print("Value of x: ")
  print(xc52);
except np.linalg.LinAlgError as err:
        # your error handling block
        print(str(err))


Singular matrix


In [99]:
#C.6 Two non-trivial solutions Fx=0
l,v,r= np.linalg.svd(fff);
#print(l)
#print(v)
#print(r)
print(np.dot(fff,r))

[[-2.23606798  0.        ]
 [-4.47213595  0.        ]]


In [81]:
#C.7 the only solution x to the equation Dx=0
c71=np.array([0, 0])
xc72= np.linalg.solve(ddd, c71)

print("Value of x: ")
print(xc72);
np.allclose(np.dot(ddd, xc72), c71)

Value of x: 
[0. 0.]


True